### ISSUE TITLE
Error: Could not find 'bundler'

### ISSUE THREAD

**Issue by misaelnieto** [helaili/jekyll-action#13]
Hi, I tried using jekyll-action:

```yml
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: helaili/jekyll-action@1.0
```

The action/job fails with this error:

```
 Build container for action use: '/home/runner/work/_actions/helaili/jekyll-action/1.0/Dockerfile'.
/usr/bin/docker build -t e87b52:348d160bb4eb4af7bba8b5057a9c247e "/home/runner/work/_actions/helaili/jekyll-action/1.0"
Sending build context to Docker daemon  11.78kB

Step 1/14 : FROM ruby:2-slim
[...]
Processing triggers for libgdk-pixbuf2.0-0:amd64 (2.38.1+dfsg-1) ...
/usr/local/lib/ruby/2.7.0/rubygems.rb:275:in `find_spec_for_exe': Could not find 'bundler' (1.17.3) required by `$BUNDLER_VERSION`. (Gem::GemNotFoundException)
To update to the latest version installed on your system, run `bundle update --bundler`.
To install the missing version, run `gem install bundler:1.17.3`
	from /usr/local/lib/ruby/2.7.0/rubygems.rb:294:in `activate_bin_path'
	from /usr/local/bin/bundle:23:in `<main>'
The command '/bin/sh -c apt-get update &&     apt-get install --no-install-recommends -y         bats         build-essential         ca-certificates         curl         libffi6         make         shellcheck         libffi6         git-all     && bundle config --global silence_root_warning 1' returned a non-zero code: 1

##[error]Docker build failed with exit code 1
```
Any idea how to fix this?

**Comment by helaili** [comment]
This is fixed with #14
